### ISSUE TITLE
Research task: Collect data on how long a release takes

### ISSUE THREAD

**Issue by LappleApple** [kubernetes-sigs/promo-tools#1124]
## Objectives

- Find out how much time each release step is taking, and document it
- Use findings as the basis for making a decision about which release step is the best candidate for breaking down in the monolith

## Context and things to think about while working on this task
- Should be done by someone actively managing a release.
- It takes 30-40 mins to cut a K8s release. Sometimes we create two releases. If you do four releases (patches) this extends the time to ~six hours. 
- Used to take three hours (BUT there was less involved).

## Acceptance criteria
- Create a table showing time lengths of different release scenarios
- Share table/findings with SIG for input and feedback--post in Slack channel and (if possible) present at a community meeting

**Comment by saschagrunert** [comment]
Copying the data from [v1.29.0-rc.2](https://github.com/kubernetes/sig-release/issues/2388#issuecomment-1844993506):

| Step | Duration | Notes |
|:-|-:| :- |
| Issue creation, testgrid shots, slack announcement | 5min | |
| Mock stage | 1h 10min| |
| Mock release | 20min | |
| NoMock stage (building release) | 1h 12min | |
| NoMock stage (building packages) | +4h| Waiting for packages to be published timed out and took hours after the step |
| Image promotion (time to merge) | 4h | Handover between timezones |
| Image promotion (waiting for job) | 5min| Was the only job in the merge queue |
| Image promotion (job duration) | 33min| Failed on signature replication because of too many requests |
| NoMock release | 20min| |

**Comment by xmudrii** [comment]
@saschagrunert This is done, should we close this issue?

**Comment by saschagrunert** [comment]
Sure

/close
