### ISSUE TITLE
Spike: find out why the post-k8sio-image-promo job takes so long

### ISSUE THREAD

**Issue by LappleApple** [kubernetes-sigs/promo-tools#1125]
## Objective 
- Find out why the post-k8sio-image-promo job takes so long (2-3 hours), so that we may find ways to shorten its running time
- Draft a *brief* proposal identifying a few possible ways to solve it, ideally addressing these questions: A) Could we make running the post-k8sio-image-promo job  parallel or async? B) Could a 10-min wait per CI job that does the promotion be possible?

## Context and things to think about while working on this task
- Cutting a K8s releases takes 30-40 mins. Doing four releases (patches) extends the time to ~six hours. Used to take three hours (keep in mind that there's more to the process nowadays).
- We need to add more mirrors, but this depends on tradeoffs and length of release time
- Parallelization led to rate limits, so in the past we stopped trying to figure out which type of artifact was extending the length of time

![Image](https://github.com/kubernetes-sigs/promo-tools/assets/2453640/f4c08f06-224b-4c83-8546-c2a2d46159ec)

![Image](https://github.com/kubernetes-sigs/promo-tools/assets/2453640/e5402ccf-2f00-4772-8fef-9baeedfc2c82)

**Comment by ameukam** [comment]
One thing affecting the length of execution is the number of container registries used to serve the images promoted. 

From 3 GCR registries to more than 10 AR repositories.

**Comment by meganwolf0** [comment]
To try and address this issue, some effort was made to grab a sampling of image promo jobs that were created for various image promotions (see file name + date for reference back to source). The idea was to see what share of the total time was spent in each step of the promotion.

File | get promotion edges |  validate signatures  | promote images | signing images | total time | # promos
|-----|-----|-----|-----|-----|-----|-----|
| gcp-filestore-csi-driver-01-23.txt | 9.6% | 1.1% | 24.2% | 64.8% | 0:04:57.240000 | 20 |
| kueue-01-18.txt | 14.3% | 1.8% | 17.2% | 66.5% | 0:03:00.802000 | 20 |
| cluster-api-azure-controller-01-18.txt | 13.7% | 1.3% | 23.0% | 61.6% | 0:03:44.085000 | 20 |
| metrics-server-01-23.txt | 8.8% | 1.0% | 16.0% | 74.1% | 0:04:52.458000 | 20 |
| ibm-powervs-block-csi-driver-01-26.txt | 11.4% | 1.1% | 18.6% | 68.4% | 0:04:09.189000 | 22 |
| ingress-nginx-controller-01-23.txt | 10.7% | 1.3% | 33.0% | 54.8% | 0:07:04.906000 | 40 |
| ingress-nginx-controller-01-26.txt | 13.1% | 1.3% | 34.6% | 50.8% | 0:06:35.702000 | 44 |
| kubecross-01-19.txt | 10.7% | 1.4% | 60.5% | 27.3% | 0:15:03.641000 | 100 |
| kube-cross-01-26.txt | 15.6% | 2.3% | 56.2% | 25.6% | 0:11:31.794000 | 110 |
| go-runner-01-19.txt | 20.6% | 3.1% | 20.1% | 56.0% | 0:08:09.598000 | 120 |
| debian-base-01-27.txt | 21.8% | 3.3% | 23.8% | 50.9% | 0:07:38.530000 | 132 |
| provider-os-01-18.txt | 14.6% | 2.5% | 52.1% | 30.7% | 0:12:18.403000 | 140 |
| kube-cross-01-10.txt | 5.0% | 3.7% | 75.5% | 15.9% | 0:31:11.250000 | 500 |

For more images, the actual promotion itself was the greatest share of total time, for fewer images the validating/signing/replicating image portion took up a larger portion of the job.

(Wondering if variability in the time it takes to do these promotions are in part driven by network considerations that may vary day to day? Would it make sense to schedule these for traffic optimization?)

You can see the break down of the pieces of the jobs, for a lot of images, it’s undoubtedly the “promote images” portion that takes the most time. To parallelize some of this work, you’d need to have different jobs making requests so that rate limiting could be circumvented.

(Does multiple machines bypass the rate limiting? Is it limited by user credentials, target registry, or solely from origin IP?)
