### ISSUE TITLE
Digests should not be not mutable

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/promo-tools#277]
#### What happened:

Noticed in https://github.com/kubernetes/k8s.io/pull/1414, a user was able to mutate a digest:tag mapping.

#### What you expected to happen:

This should be a violation of the promoter logic and the presubmit should've blocked the merge. 

/assign @listx 
/priority critical-urgent
cc: @thockin @kubernetes-sigs/release-engineering 

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by listx** [comment]
Let me try reproducing; this is obviously a bug.

**Comment by listx** [comment]
I did some digging into the logs. To simplify the situation, what happened in the referenced PR is, a few days ago (Nov 8?) a PR was merged with digest A (just using this short name for simplicity), and then a new PR was merged https://github.com/kubernetes/k8s.io/pull/1414 with digest B for the same tag. The promoter did not complain.

What happened here is, when the PR with digest A was merged, the promotion run here https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-k8sio-image-promo/1325333146882805760 detected that digest A was invalid (it could not find such an image from the staging registry (newlines added for legibility)):

```
E1108 07:03:58.004307      12 inventory.go:495] edge {{gcr.io/k8s-staging-capi-openstack   true} {capi-openstack-controller v0.3.2}
 sha256:3e5906f953f4250534be17ea349401d6871d1db2f5f6df60bc219564eb1e73e5 {asia.gcr.io/k8s-artifacts-prod/capi-openstack k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com  false} {capi-openstack-controller v0.3.2}}: 
skipping gcr.io/k8s-staging-capi-openstack/capi-openstack-controller@sha256:3e5906f953f4250534be17ea349401d6871d1db2f5f6df60bc219564eb1e73e5 
because it is _LOST_ (can't find it in src registry!)
```

As a result, the image promotion run for digest A was a NOP. So when https://github.com/kubernetes/k8s.io/pull/1414 rolled around a few days later, the promoter was perfectly happy to use it, as *no tags needed to be mutated* as it was a promotion on the "first impression" as far as the promoter was concerned.

That being said, the presubmit check should have complained, which it did, although its complaint was buried underneath a sea of other log messages. The primary reason we don't exit with an error for so-called "lost" images because this is expected in the long term for all of the images promoted from staging repos, which are considered ephemeral.

The right thing to do here is to probably separate "images being promoted in this PR" vs "images that have already been promoted", and to treat the former category differently than the latter. As a rough sketch, the first category can be generated already today by dumping all images in the promoter manifests at revision X and a second "dump" at revision Y, then performing a line-by-line delta. The "dump" command is

```
 bazel run //:cip -- -thin-manifest-dir $HOME/go/src/github.com/kubernetes/k8s.io/k8s.gcr.io -manifest-based-snapshot-of=us.gcr.io/k8s-artifacts-prod -output-format=CSV
```

and this will dump each digest on a single line, like this (`->` arrow added for legibility):

```
 $ bazel run //:cip -- -thin-manifest-dir $HOME/go/src/github.com/kubernetes/k8s.io/k8s.gcr.io -manifest-based-snapshot-of=us.gcr.io/k8s-artifacts-prod -output-format=CSV 2>/dev/null | grep capi-openstack-controller
capi-openstack/capi-openstack-controller@sha256:3d50392501235237a152478ba7e71ac3c3a56b5c0652ceb616bc6c914d14d5f5,capi-openstack/capi-openstack-controller:v0.3.1
capi-openstack/capi-openstack-controller@sha256:6e6acd92a43715fc8ad2386da3eae2d255869096c4f15c509774bbb44dcaad44,capi-openstack/capi-openstack-controller:v0.2.0
capi-openstack/capi-openstack-controller@sha256:9c48899deaed50c1950b1c3c22e909890cd93824282f5080fcee20f468fe93ef,capi-openstack/capi-openstack-controller:v0.3.0-rc.0
-> capi-openstack/capi-openstack-controller@sha256:cfdd7a67771e7a3fd956205c3351ad116e912b47982a95902b120bba036d7775,capi-openstack/capi-openstack-controller:v0.3.2
capi-openstack/capi-openstack-controller@sha256:e57a0a825a4d7173c0b530bf112b61902dd867a792392e689e19cbafc99ecad5,capi-openstack/capi-openstack-controller:v0.3.0
```

The above is using the `master` branch of `kubernetes/k8s.io` at `20dd42a9db48ffe40f5f150d0fe012f4bc18265a
`. If I instead check out the older version with digest A in it (commit `61ddd64472507d22cd149023631b9b3db724bd7f`), I instead get:

```
 $ bazel run //:cip -- -thin-manifest-dir $HOME/go/src/github.com/kubernetes/k8s.io/k8s.gcr.io -manifest-based-snapshot-of=us.gcr.io/k8s-artifacts-prod -output-format=CSV 2>/dev/null | grep capi-openstack-controller
capi-openstack/capi-openstack-controller@sha256:3d50392501235237a152478ba7e71ac3c3a56b5c0652ceb616bc6c914d14d5f5,capi-openstack/capi-openstack-controller:v0.3.1
-> capi-openstack/capi-openstack-controller@sha256:3e5906f953f4250534be17ea349401d6871d1db2f5f6df60bc219564eb1e73e5,capi-openstack/capi-openstack-controller:v0.3.2
capi-openstack/capi-openstack-controller@sha256:6e6acd92a43715fc8ad2386da3eae2d255869096c4f15c509774bbb44dcaad44,capi-openstack/capi-openstack-controller:v0.2.0
capi-openstack/capi-openstack-controller@sha256:9c48899deaed50c1950b1c3c22e909890cd93824282f5080fcee20f468fe93ef,capi-openstack/capi-openstack-controller:v0.3.0-rc.0
capi-openstack/capi-openstack-controller@sha256:e57a0a825a4d7173c0b530bf112b61902dd867a792392e689e19cbafc99ecad5,capi-openstack/capi-openstack-controller:v0.3.0
```

(notice how the line moved because the lines are sorted by digest first, and the digest changed).

So I think the pieces are there to add this into the presubmit job. The only annoying thing is that the current entrypoint for the presubmit job is the raw `cip` go binary, so we'd have to add in the "compare these 2 different versions of the repository" logic in Go. It may be possible to use an in-memory filesystem for the git repo to avoid checking out the argument to `-thin-manifest-dir` on disk, although such concerns are probably fine to ignore for the Prow throwaway environment the presubmit job runs in.

@justaugustus I think we can de-escalate this issue for now.

**Comment by justaugustus** [comment]
Thanks for the write-up, Linus!
/remove-priority critical-urgent
/priority important-soon

**Comment by aledbf** [comment]
@listx from the example in the readme https://github.com/kubernetes-sigs/k8s-container-image-promoter#plain-manifest-example is not clear that is not allowed to change a tag, in particular, `latest`

**Comment by cpanato** [comment]
/remove-lifecycle rotten

If I can have some pointers I can work on this issue

cc @justaugustus @listx

**Comment by matglas** [comment]
Looks like an item that need rotten removed and important enough to keep on the backlog right?
