### ISSUE TITLE
cip-mm sort by tag instead of checksum

### ISSUE THREAD

**Issue by mrueg** [kubernetes-sigs/promo-tools#473]
#### What would you like to be added:
Currently, if you use cip-mm to promote images, it sorts the generated file by the checksum of the promoted container images. Ideally it would allow sorting the generated file by tag instead or have an option to provide that as a argument.

#### Why is this needed:
If you promote images for multiple architectures it makes it very difficult to spot if all of them are there when looking at the file.
See for example: https://github.com/kubernetes/k8s.io/pull/2595/files

**Comment by justaugustus** [comment]
Hey @mrueg, thanks for filing this (and for using the tools here!)
First up, I want to point out `kpromo pr`, which includes much of the functionality of `cip-mm` and should be your go-to tool for creating image promotion PRs. You can read more about it here: https://github.com/kubernetes-sigs/promo-tools/blob/main/docs/promotion-pull-requests.md

>  it sorts the generated file by the checksum of the promoted container images. Ideally it would allow sorting the generated file by tag instead or have an option to provide that as a argument.

Now, onto this question...
It's actually something I asked when I started using the tool.
The manifest format is a `map[string][]string` https://github.com/kubernetes-sigs/promo-tools/blob/b245668212a77e73f0f862c9b3f740ea88f1502f/image/image.go#L47-L49

to support mapping a digest to multiple tags, which you can see an example of here: https://github.com/kubernetes/k8s.io/blob/48f96e52a326b0b7ec09ea29de18be9368533950/k8s.gcr.io/images/k8s-staging-artifact-promoter/images.yaml#L27

I agree that this is maybe not intuitive and I'm not saying that we couldn't change it, but it would:
- affect the way the promoter reads in images
- require us to update all manifests to support this

@kubernetes-sigs/release-engineering @listx -- curious to hear your thoughts here.

**Comment by mrueg** [comment]
Thanks for creating those tools and taking the time to answer this request @justaugustus 
I'll update our downstream doc accordingly and will mention kpromo there https://github.com/kubernetes/kube-state-metrics/blob/master/RELEASE.md#prepare-your-release


On the second part, I can see that it is a larger change and agree that it might have only little benefit eventually. For updating all manifests, that could be done in a single batch probably. I haven't thought about the option to have multiple tags on a single digest. I guess for those cases sorting will be difficult.

**Comment by puerco** [comment]
I agree with this, making sure all intended images in the promo PRs is cumbersome. 

I think, however, that it's important to treat separately things intended to be read by machines from those intended to be read by humans.

In this particular case I think I would favor a clear overview of changes in the command line output and having a summary of changes in the PR body for human consumption while leaving the data files as they are for machines to read.

**Comment by listx** [comment]
We should move away from expecting humans to examine the YAMLs directly and leave that instead up to a tool. Said tool was proposed a while back here https://github.com/kubernetes-sigs/promo-tools/issues/254, although it didn't gain enough traction.

To make an analogy, it's like how Git saves data under .git/objects/... but gives you the `git diff/log/etc` tooling to see human-friendly commit information (Git does not expect human users to browse .git/objects/... folder directly). I think the same thing applies here as the YAML manifests become ever larger and becomes difficult to reason about (when put under traditional text-based tooling like `diff`).

Separately, I'd like to state for the record that I haven't been able to help maintain this project as much as I would have liked due to new work commitments. But in my absence, please defer to @justaugustus.

**Comment by cpanato** [comment]
i did a pr while back https://github.com/kubernetes-sigs/promo-tools/pull/251 and we discussed this.

**Comment by CecileRobertMichon** [comment]
cc @vincepri @fabriziopandini since we had a similar question when try to use kpromo for Cluster API images

**Comment by fabriziopandini** [comment]
Thanks @CecileRobertMichon for pointing to this thread!
While I understand the reasoning about YAML for machines, I think that changing the ordering to tag, or possibly image/tag, is a small improvement that provides great benefits for the people reviewing the generated PRs.

Rephrasing a little bit, given that the generated PRs requires human intervention and PRs diff shows YAML, IMO a different ordering will be beneficial for all the promo tool users.

**Comment by CecileRobertMichon** [comment]
I wrote a POC of what this could look like just to show that it's possible. Code is a little spaghetti but it could probably be cleaned up a bit.

result PR: https://github.com/kubernetes/k8s.io/pull/3264
branch: https://github.com/kubernetes-sigs/promo-tools/compare/main...CecileRobertMichon:sort-by-tag

**Comment by fabriziopandini** [comment]
+1, this makes this much easier to read while looking at the code

**Comment by CecileRobertMichon** [comment]
One question about the statement you made above @justaugustus:

> I'm not saying that we couldn't change it, but it would:
> - affect the way the promoter reads in images
> - require us to update all manifests to support this

I'm wondering if that's actually required, since some manifests, eg. [cluster-api](https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/images/k8s-staging-cluster-api/images.yaml), are not currently sorted by digest since they are manually written by humans and haven't been using the promo-tools so far, and it still works.

**Comment by CecileRobertMichon** [comment]
opened https://github.com/kubernetes-sigs/promo-tools/pull/493, please review

**Comment by justaugustus** [comment]
(Tracking `cip-mm` deprecation in https://github.com/kubernetes-sigs/promo-tools/pull/507.)
