### ISSUE TITLE
Deprecate `cip-mm`

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/promo-tools#508]
Hey @mrueg, thanks for filing this (and for using the tools here!)
First up, I want to point out `kpromo pr`, which includes much of the functionality of `cip-mm` and should be your go-to tool for creating image promotion PRs. You can read more about it here: https://github.com/kubernetes-sigs/promo-tools/blob/main/docs/promotion-pull-requests.md

>  it sorts the generated file by the checksum of the promoted container images. Ideally it would allow sorting the generated file by tag instead or have an option to provide that as a argument.

Now, onto this question...
It's actually something I asked when I started using the tool.
The manifest format is a `map[string][]string` https://github.com/kubernetes-sigs/promo-tools/blob/b245668212a77e73f0f862c9b3f740ea88f1502f/image/image.go#L47-L49

to support mapping a digest to multiple tags, which you can see an example of here: https://github.com/kubernetes/k8s.io/blob/48f96e52a326b0b7ec09ea29de18be9368533950/k8s.gcr.io/images/k8s-staging-artifact-promoter/images.yaml#L27

I agree that this is maybe not intuitive and I'm not saying that we couldn't change it, but it would:
- affect the way the promoter reads in images
- require us to update all manifests to support this

@kubernetes-sigs/release-engineering @listx -- curious to hear your thoughts here.

_Originally posted by @justaugustus in https://github.com/kubernetes-sigs/promo-tools/issues/473#issuecomment-991167871_

**Comment by listx** [comment]
Ideally we humans shouldn't have to read the YAMLs directly --- sometimes the configurations can get very long and difficult to read directly. I.e., there should be a tool that can display things in a more sensible way.

If there is additional tooling available, it would make the map key ordering in YAML an obsolete discussion (because the ordering logic would reside in the tool, not in how we write out the YAML).
